[project]
name = "baseplate-uv-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "baseplate>=2.7.0",
    "pyramid>=2.0.2",
    "sqlalchemy>=2.0.35",
]
